### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by jlkiri** [addaleax/gyp-parser#1]
Am I right that this lib can not serialize a parsed gyp?

**Comment by addaleax** [comment]
@jlkiri Yes, that’s right – but you don’t really need that in JS anyway :)

https://github.com/mongodb-js/boxednode/blob/23dfdfc8908fa83d174ede6f7ce855a61ae96855/src/native-addons.ts#L39-L41

**Comment by jlkiri** [comment]
I see, so `JSON.stringify` can deal with it? Interesting!

**Comment by addaleax** [comment]
Yes, GYP is essentially Python object literals, and JSON is essentially a subset of that (up to things like `null` which don’t generally occur in GYP)

**Comment by jlkiri** [comment]
Ok, thank you!
